### ISSUE TITLE
BrowserStackTunnel: changing default ports

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/digdug#25]
I've just received the following mail from BrowserStack support:

> We noticed that you are using "http://hub.browserstack.com:4444" while running your Selenium tests on BrowserStack Automate. We would recommend that you switch to either port 80 ("http://hub.browserstack.com:80") or port 443 ("https://hub.browserstack.com:443"), because we will be disabling port 4444 by 5th May, 2016. We are in the process of making modifications which will improve the overall performance of your tests via port 80 and 443.

While it is possible to defer this configuration to user-land (see below), that's not desireable…

```js
{
  tunnel: "BrowserStackTunnel",
  tunnelOptions: {
     hostname: "hub.browserstack.com",
     protocol: "https",
     port: 443
  },
}
```

**Comment by jason0x43** [comment]
As of commit 45e89e5b1 the default BrowserStack port is now 443 and the default protocol is 'https'.
