### ISSUE TITLE
Fix the verbose flag in SeleniumTunnel

### ISSUE THREAD

**Issue by jason0x43** [theintern/digdug#43]
In Selenium 3, the `-debug` flag takes an argument (i.e., `-debug true`).

Also, when `verbose` mode is enabled, we shouldn't remove the output logger in `_start` after the tunnel is fully started.

**Comment by jason0x43** [comment]
Fixed in 0338cb8 and 2ba842e

**Comment by vladikoff** [comment]
Thanks so much @jason0x43
