### ISSUE TITLE
Java requirement and SeleniumTunnel

### ISSUE THREAD

**Issue by kitsonk** [theintern/digdug#48]
Using SeleniumTunnel requires a JDK to be available in the environment though there is no mention of this in the DigDug documentation and no graceful checks for this when installing the package.  There should be some way of handling this gracefully and documenting the requirement.

References dojo/cli-test-intern#51

**Comment by jason0x43** [comment]
To be fair, both the [Dig Dug docs](https://theintern.github.io/digdug/module-digdug_SeleniumTunnel.html) and the [Intern 3 docs](http://theintern.github.io/intern/#local-selenium) do mention that Java needs to be installed to use SeleniumTunnel. In any case, though, Dig Dug could give a more useful error when Java isn't present (currently it just gives a Node `Error: spawn java ENOENT` error).

This is related to https://github.com/theintern/digdug/issues/46, which would provide a means to interact with WebDrivers directly.

**Comment by edhager** [comment]
For the cases when Java is needed and not installed, it would be nice if digdug produced a "please install a Java VM" message.

**Comment by inad9300** [comment]
May be a regression... May be a bug. If you specify "pretty" as a reporter, the Java message is not displayed. It took me a while!
