### ISSUE TITLE
Verbose mode breaks with Selenium 3.5.0

### ISSUE THREAD

**Issue by jason0x43** [theintern/digdug#51]
Passing `-debug true` to Selenium 3.5.0 causes Selenium to error out.

See https://github.com/theintern/digdug/commit/2ba842e4c610f15859649d2c22201d50ca5fedb5#commitcomment-24727009

**Comment by jason0x43** [comment]
Well that's just annoying. It looks like 3.0.0 used just `-debug`, while 3.1.0-3.4.0 used `-debug true`, then 3.5.0 is back to `-debug`.

**Comment by vladikoff** [comment]
@jason0x43 hey sorry, will the fix be available in intern ~3?

**Comment by jason0x43** [comment]
I can do a 1.6.5 point release.

**Comment by vladikoff** [comment]
@jason0x43 that would be very helpful!! 👍

**Comment by HorvathAkosPeter** [comment]
I use 3.141.59, and nothing works. `-debug true` gives an error message, `-debug` and `--debug` simply doesn't do anything.
