### ISSUE TITLE
Failed to start tunnel - null or selenium tunnel

### ISSUE THREAD

**Issue by AmirTugi** [theintern/digdug#61]
Running a intern locally with null + manual chromedriver or using selenium tunnel works fine
But when I try to run the same intern on Jenkins, it downloads the tunnels (null/ selenium - why does it need to download null tunnel anyway?) and then throws: 
```
Tunnel download: 100.000%
Failed to start tunnel[K
Stopping[K
Unhandled error: TypeError: invalid pid
    at process.kill (internal/process.js:168:13)
    at killPid (/deployment/node_modules/tree-kill/index.js:73:17)
    at /deployment/node_modules/tree-kill/index.js:55:17
    at Array.forEach (<anonymous>)
```

What could cause this?

intern version: 4.2.0

*EDIT* - I simulated the issue locally. The problem seems to be with the docker which intern runs on.

**Comment by jason0x43** [comment]
Possible causes:

1. For null tunnel, did you manually start Selenium or chromedriver on the Jenkins server? null tunnel only works with an already-running webdriver server.
2. For selenium tunnel, does the Jenkins server have Java? Selenium requires Java.

When null tunnel is initialized it simply attempts to connect to an already running webdriver server or Selenium.

Selenium tunnel handles more of the webdriver startup process. When the Selenium tunnel is initialized it downloads Selenium and any necessary webdrivers (this is why you see the 'downloading' message), and then starts Selenium. Note that Java is required to run Selenium.

**Comment by jason0x43** [comment]
I agree, the error message could definitely be better; there's actually an [open issue](https://github.com/theintern/digdug/issues/48) for that.

Regarding how to install `java` in your docker container, it depends on your setup, but there are [numerous](https://www.atlassian.com/blog/software-teams/deploy-java-apps-with-docker-awesome) [examples](https://stackoverflow.com/questions/42513642/installing-java-on-docker-in-docker-image) online.
