### ISSUE TITLE
edge or MicrosoftEdge or ?

### ISSUE THREAD

**Issue by dylans** [theintern/digdug#63]
When configuring with Edge locally, is it edge or MicrosoftEdge?

Please verify and update if necessary at https://theintern.io/docs.html#Dig%20Dug/2/api/SeleniumTunnel/seleniumtunnel-1

**Comment by jason0x43** [comment]
Ah. Well, it's 'MicrosoftEdge' for the Selenium capability, but it's currently 'edge' for the driver name (`"tunnelOptions": { "drivers": ["edge"] }`), which is used to tell the selenium tunnel which drivers it should download. The tunnel will be updated to support 'MicrosoftEdge' (and 'internet explorer', which is currently just 'ie') as valid driver names.

**Comment by jason0x43** [comment]
And of course the docs still need updating.
