### ISSUE TITLE
Downloading Selenium and Drivers via HTTPS through Proxy fails

### ISSUE THREAD

**Issue by sebastianfrey** [theintern/digdug#65]
Currently I am facing a problem, when I use Intern behind a corporate proxy (squid 3). The problem is, as already mentioned in the title, that `digdug` fails to download Selenium and related Drivers via HTTPS and proxy.

The problem seems to occur in `dojo/core`'s request provider for node, which likely does not establish an HTTP Connect via the proxy.

Excerpt from the proxy's log file caused by Intern:

`192.168.81.63 NONE/501 3812 GET https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz - HIER_NONE/- text/html`

**Comment by jason0x43** [comment]
As of 2.2.0, Dig Dug no longer uses @dojo/core to manage requests; is this issue still occurring?

**Comment by sebastianfrey** [comment]
After upgrading to Intern 4.3.3 which uses Dig Dug 2.2.0 I recive the following error when I try to start my tests:
 
```
Error: write EPROTO 139696495142720:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

  at _errnoException  <util.js:992:11>
  at WriteWrap.afterWrite [as oncomplete]  <net.js:864:14>
```
When I copy the drivers manually to `node_modles/@theintern/digdug/selenium-standalone` everything works as expected.

**Comment by jason0x43** [comment]
Is this error still occurring? If so, could you try wiping out your local node modules and installing intern again? I haven't seen any other reports of this error, so I thought it might have been something transient.

**Comment by sebastianfrey** [comment]
Wiped out my local node modules and did a fresh install as suggested by you. Unfortunately the error still occurs. Probably the issue is related to [axios#925](https://github.com/axios/axios/issues/925)?

**Comment by jason0x43** [comment]
Well drat, we just can't win with proxies.

**Comment by jason0x43** [comment]
I agree, though, that axios issue looks like the same thing.

**Comment by jason0x43** [comment]
Closing this in favor of theintern/intern#1065.
