### ISSUE TITLE
Update webdriver versions one last time

### ISSUE THREAD

**Issue by r33beers** [theintern/digdug#79]
I'm sad to see this repository be deprecated. I'd like to continue using it for a little while longer until I have a chance to migrate to something else. Could you upgrade the webdriver versions used to support the latest browsers (specifically Chrome 80) to buy time to migrate off?

**Comment by jason0x43** [comment]
We can definitely update the driver versions, and bug fixes will still make it here.

We're also not ruling out the possibility of releasing future versions of digdug (or something equivalent), just not from this repo.

**Comment by r33beers** [comment]
Thank you. Chrome 80 support would be greatly appreciated as soon as possible, and I'll follow https://github.com/theintern/intern/issues/1115 for updates on the future of digdug as an independent package.

**Comment by jason0x43** [comment]
The Chrome and Edge Chromium drivers were updated in 5585b72 and released in v2.4.4.
